export const data = {
  products: [
    {
      id: 1,
      categoryId: 1,
      title: "Samsung Galaxy S7",
      price: 599.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 1,
    },
    {
      id: 2,
      categoryId: 2,
      title: "google pixel ",
      price: 499.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 1,
    },
    {
      id: 3,
      categoryId: 3,
      title: "Xiaomi Redmi Note 2",
      price: 699.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 1,
    },
    {
      id: 4,
      categoryId: 1,
      title: "Samsung Galaxy S9",
      price: 599.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 23,
    },
    {
      id: 5,
      categoryId: 2,
      title: "google pixel 10 ",
      price: 499.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 33,
    },
    {
      id: 6,
      categoryId: 3,
      title: "Xiaomi Redmi Note 4",
      price: 699.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 43,
    },
    {
      id: 7,
      categoryId: 1,
      title: "Samsung Galaxy S8",
      price: 599.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 12,
    },
    {
      id: 8,
      categoryId: 2,
      title: "google pixel 5 ",
      price: 499.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 14,
    },
    {
      id: 9,
      categoryId: 3,
      title: "Xiaomi Redmi Note 3",
      price: 699.99,
      img: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTsM3Le5Vb7UtlS8fgH-vCTsvlqExoYxv3SBm9krj-z6HT5TLV0eglxMq2hoQ9lYY83VyOPt41ynDhn6V5nbMC1pGmni5zjQL0wNrqaGztilkDIszkLsVDncw&usqp=CAc",
      amount: 15,
    },
  ],
  categories: [
    { id: 1, categoryName: "Samsung" },
    { id: 2, categoryName: "Google" },
    { id: 3, categoryName: "Xiaomi" },
  ],
};
